packages:
  - 'apps/*'
  - 'packages/*'
  - 'configs/*'

catalog:
  react: '^19.1.0'
  react-dom: '^19.1.0'
  tailwindcss: '^4.1.10'
  typescript: '5.7.3'
  lucide-react: '^0.514.0'
  tw-animate-css: '^1.3.4'
  '@types/node': '^24.0.1'
  '@types/react': '^19.1.8'
  '@types/react-dom': '^19.1.6'
  '@tailwindcss/postcss': '^4.1.10'
